meta_product_name: "Khooshal Seechurn"
meta_title: "Khooshal Seechurn - A tech and Finance Enthusiast"
meta_description: "I am actively searching for internships in the financial and technological sector"
meta_image: "my.png" # should exist in `app/assets/images/`
